# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

jobs:

- job: build
  pool: 
    name: 'Azure Pipelines'
    vmImage: ubuntu-latest
  steps:
  - checkout: self
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'ls -al $(Pipeline.Workspace)/s'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)/s'
      artifact: 'arcade-app'
      publishLocation: 'pipeline'

- job: deploy
  dependsOn: build
  pool: 
    name: 'Azure Pipelines'
    vmImage: 'windows-latest'
  steps:
  - checkout: none
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'arcade-app'
      targetPath: '$(Pipeline.Workspace)/a'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Pipeline.Workspace)/a'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: 'arcade-app'
      replaceExistingArchive: true
      quiet: true


  - task: DownloadSecureFile@1
    name: downloadPub
    inputs:
      secureFile: '$(arcade-app-pub-file)'
      retryCount: '3'

  - task: AzureRmWebAppDeployment@5
    inputs:
      ConnectionType: 'PublishProfile'
      PublishProfilePath: '$(dowloadPub.secureFilePath)'
      PublishProfilePassword: '$(app_publish_profile_password)'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

  