# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
pool: 
  name: 'Azure Pipelines'
  vmImage: ubuntu-latest

jobs:
- job: build
  steps:
  - checkout: self
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)'
      artifact: 'arcade-app'
      publishLocation: 'pipeline'

- job: deploy
  dependsOn: build

  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'arcade-app'
      targetPath: '$(Pipeline.Workspace)'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'ls -alR $(Pipeline.Workspace)'

  - task: AzureRmWebAppDeployment@5
    inputs:
      ConnectionType: 'PublishProfile'
      PublishProfilePath: '$(System.DefaultWorkingDirectory)/**/*.pubxml'
      PublishProfilePassword: '$(app_publish_profile)'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

  